// <auto-generated />
using CarParkAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CarParkAPI.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("CarParkAPI.Models.CarPark", b =>
                {
                    b.Property<string>("CarParkNo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("CarParkDecks")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CarParkTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("GantryHeight")
                        .HasColumnType("TEXT");

                    b.Property<bool>("HasBasement")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ParkingSystemId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("XCoord")
                        .HasColumnType("REAL");

                    b.Property<double>("YCoord")
                        .HasColumnType("REAL");

                    b.HasKey("CarParkNo");

                    b.HasIndex("CarParkTypeId");

                    b.HasIndex("GantryHeight");

                    b.HasIndex("ParkingSystemId");

                    b.ToTable("CarParks");
                });

            modelBuilder.Entity("CarParkAPI.Models.CarParkType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("CarParkTypes");
                });

            modelBuilder.Entity("CarParkAPI.Models.ParkingPolicy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CarParkNo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FreeParking")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("OffersNightParking")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ShortTermParking")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CarParkNo")
                        .IsUnique();

                    b.HasIndex("FreeParking");

                    b.HasIndex("OffersNightParking");

                    b.ToTable("ParkingPolicies");
                });

            modelBuilder.Entity("CarParkAPI.Models.ParkingSystem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ParkingSystems");
                });

            modelBuilder.Entity("CarParkAPI.Models.UserFavorite", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CarParkNo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CarParkNo1")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CarParkNo1");

                    b.ToTable("UserFavorites");
                });

            modelBuilder.Entity("CarParkAPI.Models.CarPark", b =>
                {
                    b.HasOne("CarParkAPI.Models.CarParkType", "CarParkType")
                        .WithMany()
                        .HasForeignKey("CarParkTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CarParkAPI.Models.ParkingSystem", "ParkingSystem")
                        .WithMany()
                        .HasForeignKey("ParkingSystemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CarParkType");

                    b.Navigation("ParkingSystem");
                });

            modelBuilder.Entity("CarParkAPI.Models.ParkingPolicy", b =>
                {
                    b.HasOne("CarParkAPI.Models.CarPark", "CarPark")
                        .WithOne("ParkingPolicy")
                        .HasForeignKey("CarParkAPI.Models.ParkingPolicy", "CarParkNo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CarPark");
                });

            modelBuilder.Entity("CarParkAPI.Models.UserFavorite", b =>
                {
                    b.HasOne("CarParkAPI.Models.CarPark", "CarPark")
                        .WithMany()
                        .HasForeignKey("CarParkNo1");

                    b.Navigation("CarPark");
                });

            modelBuilder.Entity("CarParkAPI.Models.CarPark", b =>
                {
                    b.Navigation("ParkingPolicy")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
